name: Build

on:
  push:
    branches: 
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Auto commit
      CI_COMMIT_AUTHOR: github-actions[bot]
      CI_COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com

    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: npm install rollup rollup-plugin-scss sass
      
      - name: Build JS
        run: npm run build
      
      - name: Build Css
        run: npm run build

      - name: GIT Commit Build
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git add -f dist/*
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push