name: release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_AUTHOR: github-actions[bot]
      CI_COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com

    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: npm install
      
      - name: Build JS
        run: npm run build
      
      - name: Zip dist folder
        run: zip -r dist.zip dist

      - name: Calculate checksums
        id: checksums
        run: |
          shasum dist.zip > dist.zip.sha256
          md5sum dist.zip > dist.zip.md5

      - name: Retrieve version
        run: |
            echo "TAG_NAME=$(git describe --abbrev=0)" >> $GITHUB_OUTPUT
        id: version
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip, dist.zip.sha256, dist.zip.md5"
          generateReleaseNotes: true
          commit: "main"
          tag: ${{ steps.version.outputs.TAG_NAME }}
          skipIfReleaseExists: true